# Generated by Django 5.0.6 on 2024-08-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('SID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
